### ISSUE TITLE
Cannot start ahab on Mac OS X 

### ISSUE THREAD

**Issue by mcmil** [instacart/ahab#1]
I've tried to run ahab on mac os x along with docker toolbox with the following command: `ahab --console debug $DOCKER_HOST`. 
Docker host resolves to:

```
echo $DOCKER_HOST
tcp://192.168.99.100:2376
```

I've got the following error:

```
➜  ~  ahab --console debug $DOCKER_HOST
17:21:48.430     INFO  ahab
  Under weigh.
17:21:48.442    ERROR  ahab
  It wasn't unexpected!
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ahab/__main__.py", line 20, in ahab
    Ahab(connection).listen()
  File "/Library/Python/2.7/site-packages/ahab/__init__.py", line 21, in listen
    for event in client.events(decode=True):
  File "/Library/Python/2.7/site-packages/docker/api/daemon.py", line 28, in events
    self.get(self._url('/events'), params=params, stream=True),
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 412, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',))
```

Additional info:

```
docker -v
Docker version 1.9.0, build 76d6bc9
```

I'm missing something or Docker Toolbox is not supported currently?

**Comment by solidsnack** [comment]
Thanks for reporting this issue. I don't think you're missing anything -- we just haven't tried it out using anything but the local Docker socket on Linux. We'll give this a shot.

**Comment by Matt-Hurd** [comment]
Tested out on OSX with `Docker version 18.06.0-ce, build 0ffa825` and it as expected.
